policy_name: W-61/ultrafeedback-llama3-8b-margin-dpo
precision: bf16

arenahard_v2:
  bench_name: arena-hard-v2.0
  benchmark_dir: ../data/arena-hard-v2.0
  pretty_name: ultrafeedback-llama3-8b-margin-dpo
  model_name_or_path: W-61/ultrafeedback-llama3-8b-margin-dpo
  mode: local
  backend: vllm
  endpoint_file: api_config.yaml
  judge_model: gpt-4.1
  judge_endpoint_name: gpt-4.1
  question_file: question.jsonl
  use_custom_chat_template: true
  prompt_template: ../mtbench/templates/ultrafeedback-llama3-8b-margin-dpo.jinja
  bootstrap_rounds: 100
  generation:
    batch_size: 128
    do_sample: false
    max_new_tokens: 4096
    stop_token_ids:
      - 128001
      - 128009
    temperature: 0.0
    top_p: 1.0
  vllm:
    tensor_parallel_size: 1
    trust_remote_code: false
    gpu_memory_utilization: 0.9
  transformers:
    device: cuda
    trust_remote_code: false

