dataset:
  repo_id: "Anthropic/hh-rlhf"
  data_dir: "helpful-base"
  split: "test"
  single_turn_only: true
  max_instances: null

models:
  sft: "W-61/llama-3-8b-base-sft-hh-helpful-8xh200"
  beta_dpo: "W-61/llama-3-8b-base-beta-dpo-hh-helpful-8xh200"
  margin_dpo: "W-61/llama-3-8b-base-margin-dpo-hh-helpful-8xh200"
  e_dpo: "W-61/llama-3-8b-base-epsilon-dpo-hh-helpful-8xh200"

generation:
  model_key: "beta_dpo"
  output_key: "beta_dpo"
  backend: "vllm"
  use_custom_chat_template: false
  prompt_template: "templates/llama3.txt"
  max_new_tokens: 128
  batch_size: 8
  stop_token_ids:
    - 128001
    - 128009
  device: "cuda"
  temperature: 0.7
  top_p: 0.9
  max_input_tokens: 2048
  apply_chat_template: true
  seed: 42
  extract_chosen: false
  tensor_parallel_size: 1
  gpu_memory_utilization: 0.9
  trust_remote_code: false

inputs:
  sft: "outputs/gpt_judge_HH/helpful_base/llama-3-8b-base-sft-hh-helpful-8xh200-single.json.json"
  beta_dpo: "outputs/gpt_judge_HH/helpful_base/llama-3-8b-base-beta-dpo-hh-helpful-8xh200-single.json"
  margin_dpo: "outputs/gpt_judge_HH/helpful_base/llama-3-8b-base-margin-dpo-hh-helpful-8xh200-single.json"
  e_dpo: "outputs/gpt_judge_HH/helpful_base/llama-3-8b-base-epsilon-dpo-hh-helpful-8xh200-single.json"
  chosen: "outputs/gpt_judge_HH/helpful_base/chosen_output_hh_single.json"

gpt4_oracle:
  model: "gpt-4o-2024-08-06"
  max_tokens: 256
  seed: 42
  max_retries: 5
  initial_backoff: 1.0
  max_backoff: 60.0
  system_prompt: 
  prompt_template_pairwise: |
    For the following query to a chatbot, which response is more helpful?

    Query: {instruction}

    Response A:
    {output_a}

    Response B:
    {output_b}

    FIRST provide a one-sentence comparison of the two responses and explain \
    which you feel is more helpful. SECOND, on a new line, state only "A" or \
    "B" to indicate which response is more helpful. Your response should use \
    the format:
    Comparison: <one-sentence comparison and explanation>
    More helpful: <"A" or "B">

output:
  results_file: "outputs/gpt_judge_HH/helpful_base/single_turn/chosen_vs_llama-3-8b-base-beta-dpo-hh-helpful-8xh200.jsonl"
  summary_file: "outputs/gpt_judge_HH/helpful_base/single_turn/chosen_vs_llama-3-8b-base-beta-dpo-hh-helpful-8xh200_summary.json"

judge:
  candidate_keys:
    - "chosen"
    - "beta_dpo"
