base_config: config_arenahard.yaml
run_inference: true
run_judging: false
skip_existing: true
continue_on_error: false

models:
  - model_name_or_path: W-61/llama-3-8b-base-sft-ultrachat-8xh200
    pretty_name: llama-3-8b-base-sft-ultrachat-8xh200
    overrides:
      arenahard:
        use_custom_chat_template: false

  - model_name_or_path: W-61/llama-3-8b-base-margin-dpo-ultrafeedback-8xh200
    pretty_name: llama-3-8b-base-margin-dpo-ultrafeedback-8xh200
    overrides:
      arenahard:
        use_custom_chat_template: false

  - model_name_or_path: W-61/llama-3-8b-base-beta-dpo-ultrafeedback-8xh200
    pretty_name: llama-3-8b-base-beta-dpo-ultrafeedback-8xh200
    overrides:
      arenahard:
        use_custom_chat_template: false

  - model_name_or_path: W-61/llama-3-8b-base-epsilon-dpo-ultrafeedback-8xh200
    pretty_name: llama-3-8b-base-epsilon-dpo-ultrafeedback-8xh200
    overrides:
      arenahard:
        use_custom_chat_template: false

  - model_name_or_path: jackf857/llama-3-8b-base-r-dpo-ultrafeedback-4xh200
    pretty_name: llama-3-8b-base-r-dpo-ultrafeedback-4xh200
    overrides:
      arenahard:
        use_custom_chat_template: false

  - model_name_or_path: jackf857/llama-3-8b-base-orpo-ultrafeedback-8xh200
    pretty_name: llama-3-8b-base-orpo-ultrafeedback-8xh200
    overrides:
      arenahard:
        use_custom_chat_template: false

  - model_name_or_path: jackf857/llama-3-8b-base-slic-hf-ultrafeedback-4xh200
    pretty_name: llama-3-8b-base-slic-hf-ultrafeedback-4xh200
    overrides:
      arenahard:
        use_custom_chat_template: false

  - model_name_or_path: jackf857/llama-3-8b-base-kto-ultrafeedback-8xh200
    pretty_name: llama-3-8b-base-kto-ultrafeedback-8xh200
    overrides:
      arenahard:
        use_custom_chat_template: false

  - model_name_or_path: jackf857/llama-3-8b-base-cpo-ultrafeedback-8xh200
    pretty_name: llama-3-8b-base-cpo-ultrafeedback-8xh200
    overrides:
      arenahard:
        use_custom_chat_template: false

  - model_name_or_path: jackf857/llama-3-8b-base-robust-dpo-ultrafeedback-8xh200
    pretty_name: llama-3-8b-base-robust-dpo-ultrafeedback-8xh200
    overrides:
      arenahard:
        use_custom_chat_template: false

  - model_name_or_path: jackf857/llama-3-8b-base-ipo-ultrafeedback-8xh200
    pretty_name: llama-3-8b-base-ipo-ultrafeedback-8xh200
    overrides:
      arenahard:
        use_custom_chat_template: false
