policy_name: jackf857/qwen3-8b-base-sft-ultrachat-4xh200-batch-128
precision: bf16

arenahard:
  pretty_name: qwen3-8b-base-sft-ultrachat-4xh200-batch-128
  model_name_or_path: jackf857/qwen3-8b-base-sft-ultrachat-4xh200-batch-128
  backend: vllm
  use_custom_chat_template: true
  prompt_template: templates/ultrachat-qwen3-8b-sft.jinja
  output_dir: ../outputs/arenahard/qwen3-8b-base-sft-ultrachat-4xh200-batch-128
  question_file: questions.jsonl
  judge_model: gpt-4-1106-preview
  baseline_model: gpt-4-0314
  judge_config: judge_config.yaml
  api_config: api_config.yaml
  judge_command:
    - python
    - -m
    - arena_hard_auto.judge
    - --model-answer-file
    - "{answer_file}"
    - --judge-config
    - "{judge_config}"
    - --api-config
    - "{api_config}"
    - --question-file
    - "{question_file}"
    - --output-path
    - "{judgment_file}"
  generation:
    batch_size: 128
    do_sample: false
    max_new_tokens: 4096
    stop_token_ids:
      - 151645
    temperature: 0.0
    top_p: 1.0
  vllm:
    tensor_parallel_size: 1
    trust_remote_code: false
    gpu_memory_utilization: 0.9
  transformers:
    device: cuda
    trust_remote_code: false
