policy_name: W-61/llama-3-8b-base-beta-dpo-ultrafeedback-8xh200
precision: bf16

arenahard_v2:
  bench_name: arena-hard-v2.0
  benchmark_dir: ../outputs/arenahard_v2
  pretty_name: beta-dpo
  model_name_or_path: W-61/llama-3-8b-base-beta-dpo-ultrafeedback-8xh200
  mode: local
  backend: vllm
  endpoint_file: api_config.yaml
  judge_model: gpt-4.1
  judge_endpoint_name: gpt-4.1
  judge_parallel: 1
  judge_temperature: 0.0
  judge_max_tokens: 16000
  question_file: question.jsonl
  use_custom_chat_template: true
  prompt_template: ../mtbench/templates/ultrafeedback-llama3-8b-beta-dpo.jinja
  bootstrap_rounds: 100
  generation:
    batch_size: 128
    do_sample: false
    max_new_tokens: 4096
    stop_token_ids:
      - 128001
      - 128009
    temperature: 0.0
    top_p: 1.0
  vllm:
    tensor_parallel_size: 1
    trust_remote_code: false
    gpu_memory_utilization: 0.9
  transformers:
    device: cuda
    trust_remote_code: false
